player: rewrite player using SDL2
This rewrite removes the dependency over glfw and glew in favor of SDL2.

Also disables the build of the player on the CI for MinGW/static since
it fails to build with the following errors (non-exhaustive list):

sxplayer.c:149: undefined reference to `__imp_sxplayer_get_frame'
sxplayer.c:240: undefined reference to `__imp_sxplayer_create'
sxplayer.c:246: undefined reference to `__imp_sxplayer_set_option'