mod_decoding: add missing <libavutil/channel_layout.h> include
av_get_channel_layout_string() is declared by
libavutil/channel_layout.h.

Fixes the following build error with FFmpeg >= 5.0:

 mod_decoding.c:122:5: error: implicit declaration of function
 'av_get_channel_layout_string' is invalid in C99